{'now': 1683042491, 'now_dt': '2023-05-02T15:48:11.883323Z',
 'info': {'n': True, 'geoid': 213, 'url': 'https://yandex.ru/pogoda/213?lat=55.75396&lon=37.620393', 'lat': 55.75396,
          'lon': 37.620393, 'tzinfo': {'name': 'Europe/Moscow', 'abbr': 'MSK', 'dst': False, 'offset': 10800},
          'def_pressure_mm': 747, 'def_pressure_pa': 995, 'slug': '213', 'zoom': 10, 'nr': True, 'ns': True,
          'nsr': True, 'p': False, 'f': True, '_h': False},
 'geo_object': {'district': {'id': 120540, 'name': 'Тверской район'}, 'locality': {'id': 213, 'name': 'Москва'},
                'province': {'id': 213, 'name': 'Москва'}, 'country': {'id': 225, 'name': 'Россия'}},
 'yesterday': {'temp': 8},
 'fact': {'obs_time': 1683039600, 'uptime': 1683042491, 'temp': 15, 'feels_like': 11, 'icon': 'skc_d',
          'condition': 'clear', 'cloudness': 0, 'prec_type': 0, 'prec_prob': 0, 'prec_strength': 0, 'is_thunder': False,
          'wind_speed': 2.5, 'wind_dir': 's', 'pressure_mm': 753, 'pressure_pa': 1003, 'humidity': 40, 'daytime': 'd',
          'polar': False, 'season': 'spring', 'source': 'station',
          'accum_prec': {'3': 10.846362, '1': 0.32089508, '7': 43.621975}, 'soil_moisture': 0.33, 'soil_temp': 13,
          'uv_index': 1, 'wind_gust': 4.6}, 'forecasts': [
    {'date': '2023-05-02', 'date_ts': 1682974800, 'week': 18, 'sunrise': '04:45', 'sunset': '20:07',
     'rise_begin': '04:01', 'set_end': '20:51', 'moon_code': 14, 'moon_text': 'moon-code-14', 'parts': {
        'night': {'_source': '0,1,2,3,4,5', 'temp_min': 3, 'temp_avg': 5, 'temp_max': 6, 'wind_speed': 2.5,
                  'wind_gust': 5.8, 'wind_dir': 'nw', 'pressure_mm': 752, 'pressure_pa': 1002, 'humidity': 79,
                  'soil_temp': 4, 'soil_moisture': 0.34, 'prec_mm': 0, 'prec_prob': 0, 'prec_period': 360,
                  'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'icon': 'skc_n', 'condition': 'clear',
                  'uv_index': 0, 'feels_like': 2, 'daytime': 'n', 'polar': False, 'fresh_snow_mm': 0},
        'night_short': {'_source': '0,1,2,3,4,5', 'temp': 3, 'wind_speed': 2.5, 'wind_gust': 5.8, 'wind_dir': 'nw',
                        'pressure_mm': 752, 'pressure_pa': 1002, 'humidity': 79, 'soil_temp': 4, 'soil_moisture': 0.34,
                        'prec_mm': 0, 'prec_prob': 0, 'prec_period': 360, 'cloudness': 0, 'prec_type': 0,
                        'prec_strength': 0, 'icon': 'skc_n', 'condition': 'clear', 'uv_index': 0, 'feels_like': 2,
                        'daytime': 'n', 'polar': False, 'fresh_snow_mm': 0},
        'morning': {'_source': '6,7,8,9,10,11', 'temp_min': 4, 'temp_avg': 9, 'temp_max': 13, 'wind_speed': 2.4,
                    'wind_gust': 5.6, 'wind_dir': 'w', 'pressure_mm': 755, 'pressure_pa': 1006, 'humidity': 60,
                    'soil_temp': 5, 'soil_moisture': 0.34, 'prec_mm': 0, 'prec_prob': 0, 'prec_period': 360,
                    'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'icon': 'skc_d', 'condition': 'clear',
                    'uv_index': 4, 'feels_like': 6, 'daytime': 'd', 'polar': False, 'fresh_snow_mm': 0},
        'day_short': {'_source': '6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21', 'temp': 16, 'temp_min': 4,
                      'wind_speed': 2.6, 'wind_gust': 7.1, 'wind_dir': 'w', 'pressure_mm': 754, 'pressure_pa': 1005,
                      'humidity': 46, 'soil_temp': 12, 'soil_moisture': 0.34, 'prec_mm': 0, 'prec_prob': 0,
                      'prec_period': 960, 'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'icon': 'skc_d',
                      'condition': 'clear', 'uv_index': 5, 'feels_like': 11, 'daytime': 'd', 'polar': False,
                      'fresh_snow_mm': 0},
        'evening': {'_source': '18,19,20,21', 'temp_min': 12, 'temp_avg': 14, 'temp_max': 16, 'wind_speed': 2.6,
                    'wind_gust': 7.1, 'wind_dir': 's', 'pressure_mm': 753, 'pressure_pa': 1003, 'humidity': 44,
                    'soil_temp': 13, 'soil_moisture': 0.33, 'prec_mm': 0, 'prec_prob': 0, 'prec_period': 240,
                    'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'icon': 'skc_d', 'condition': 'clear',
                    'uv_index': 1, 'feels_like': 10, 'daytime': 'd', 'polar': False, 'fresh_snow_mm': 0},
        'day': {'_source': '12,13,14,15,16,17', 'temp_min': 14, 'temp_avg': 15, 'temp_max': 16, 'wind_speed': 2.4,
                'wind_gust': 5.7, 'wind_dir': 'sw', 'pressure_mm': 755, 'pressure_pa': 1006, 'humidity': 33,
                'soil_temp': 12, 'soil_moisture': 0.34, 'prec_mm': 0, 'prec_prob': 0, 'prec_period': 360,
                'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'icon': 'skc_d', 'condition': 'clear',
                'uv_index': 5, 'feels_like': 12, 'daytime': 'd', 'polar': False, 'fresh_snow_mm': 0}}, 'hours': [
        {'hour': '0', 'hour_ts': 1682974800, 'temp': 6, 'feels_like': 2, 'icon': 'skc_n', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'nw', 'wind_speed': 2.5,
         'wind_gust': 5.8, 'pressure_mm': 751, 'pressure_pa': 1001, 'humidity': 76, 'uv_index': 0, 'soil_temp': 4,
         'soil_moisture': 0.35, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '1', 'hour_ts': 1682978400, 'temp': 5, 'feels_like': 2, 'icon': 'skc_n', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'nw', 'wind_speed': 2.5,
         'wind_gust': 5.7, 'pressure_mm': 751, 'pressure_pa': 1001, 'humidity': 77, 'uv_index': 0, 'soil_temp': 4,
         'soil_moisture': 0.35, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '2', 'hour_ts': 1682982000, 'temp': 5, 'feels_like': 1, 'icon': 'skc_n', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'nw', 'wind_speed': 2.4,
         'wind_gust': 5.4, 'pressure_mm': 752, 'pressure_pa': 1002, 'humidity': 78, 'uv_index': 0, 'soil_temp': 4,
         'soil_moisture': 0.35, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '3', 'hour_ts': 1682985600, 'temp': 4, 'feels_like': 1, 'icon': 'skc_n', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'w', 'wind_speed': 2,
         'wind_gust': 4.9, 'pressure_mm': 752, 'pressure_pa': 1002, 'humidity': 79, 'uv_index': 0, 'soil_temp': 3,
         'soil_moisture': 0.34, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '4', 'hour_ts': 1682989200, 'temp': 4, 'feels_like': 0, 'icon': 'skc_n', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'w', 'wind_speed': 1.9,
         'wind_gust': 4.1, 'pressure_mm': 753, 'pressure_pa': 1003, 'humidity': 81, 'uv_index': 0, 'soil_temp': 4,
         'soil_moisture': 0.34, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '5', 'hour_ts': 1682992800, 'temp': 3, 'feels_like': 0, 'icon': 'skc_d', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'w', 'wind_speed': 1.8,
         'wind_gust': 3.5, 'pressure_mm': 753, 'pressure_pa': 1003, 'humidity': 81, 'uv_index': 0, 'soil_temp': 4,
         'soil_moisture': 0.34, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '6', 'hour_ts': 1682996400, 'temp': 4, 'feels_like': 1, 'icon': 'skc_d', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'w', 'wind_speed': 1.8,
         'wind_gust': 3.9, 'pressure_mm': 754, 'pressure_pa': 1005, 'humidity': 80, 'uv_index': 0, 'soil_temp': 3,
         'soil_moisture': 0.34, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '7', 'hour_ts': 1683000000, 'temp': 6, 'feels_like': 3, 'icon': 'skc_d', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'w', 'wind_speed': 1.9,
         'wind_gust': 4.1, 'pressure_mm': 755, 'pressure_pa': 1006, 'humidity': 76, 'uv_index': 1, 'soil_temp': 3,
         'soil_moisture': 0.34, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '8', 'hour_ts': 1683003600, 'temp': 8, 'feels_like': 5, 'icon': 'skc_d', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'w', 'wind_speed': 2.1,
         'wind_gust': 3.9, 'pressure_mm': 755, 'pressure_pa': 1006, 'humidity': 67, 'uv_index': 1, 'soil_temp': 3,
         'soil_moisture': 0.34, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '9', 'hour_ts': 1683007200, 'temp': 11, 'feels_like': 8, 'icon': 'skc_d', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'w', 'wind_speed': 1.8,
         'wind_gust': 4.8, 'pressure_mm': 755, 'pressure_pa': 1006, 'humidity': 54, 'uv_index': 2, 'soil_temp': 7,
         'soil_moisture': 0.34, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '10', 'hour_ts': 1683010800, 'temp': 12, 'feels_like': 9, 'icon': 'skc_d', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'w', 'wind_speed': 2.2,
         'wind_gust': 5.2, 'pressure_mm': 755, 'pressure_pa': 1006, 'humidity': 45, 'uv_index': 3, 'soil_temp': 7,
         'soil_moisture': 0.35, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '11', 'hour_ts': 1683014400, 'temp': 13, 'feels_like': 10, 'icon': 'skc_d', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'w', 'wind_speed': 2.4,
         'wind_gust': 5.6, 'pressure_mm': 755, 'pressure_pa': 1006, 'humidity': 40, 'uv_index': 4, 'soil_temp': 7,
         'soil_moisture': 0.35, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '12', 'hour_ts': 1683018000, 'temp': 14, 'feels_like': 11, 'icon': 'skc_d', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'w', 'wind_speed': 2.3,
         'wind_gust': 5.7, 'pressure_mm': 755, 'pressure_pa': 1006, 'humidity': 35, 'uv_index': 4, 'soil_temp': 12,
         'soil_moisture': 0.34, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '13', 'hour_ts': 1683021600, 'temp': 14, 'feels_like': 12, 'icon': 'skc_d', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'sw', 'wind_speed': 2.4,
         'wind_gust': 5.1, 'pressure_mm': 755, 'pressure_pa': 1006, 'humidity': 34, 'uv_index': 5, 'soil_temp': 12,
         'soil_moisture': 0.34, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '14', 'hour_ts': 1683025200, 'temp': 15, 'feels_like': 12, 'icon': 'skc_d', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'sw', 'wind_speed': 2.4,
         'wind_gust': 4.8, 'pressure_mm': 755, 'pressure_pa': 1006, 'humidity': 34, 'uv_index': 4, 'soil_temp': 12,
         'soil_moisture': 0.34, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '15', 'hour_ts': 1683028800, 'temp': 16, 'feels_like': 13, 'icon': 'skc_d', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'sw', 'wind_speed': 2.1,
         'wind_gust': 4.6, 'pressure_mm': 754, 'pressure_pa': 1005, 'humidity': 32, 'uv_index': 3, 'soil_temp': 13,
         'soil_moisture': 0.33, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '16', 'hour_ts': 1683032400, 'temp': 16, 'feels_like': 12, 'icon': 'bkn_d', 'condition': 'cloudy',
         'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'sw', 'wind_speed': 2.2,
         'wind_gust': 3.5, 'pressure_mm': 754, 'pressure_pa': 1005, 'humidity': 31, 'uv_index': 2, 'soil_temp': 13,
         'soil_moisture': 0.33, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '17', 'hour_ts': 1683036000, 'temp': 16, 'feels_like': 13, 'icon': 'skc_d', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'sw', 'wind_speed': 2.3,
         'wind_gust': 3.9, 'pressure_mm': 754, 'pressure_pa': 1005, 'humidity': 33, 'uv_index': 1, 'soil_temp': 13,
         'soil_moisture': 0.33, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '18', 'hour_ts': 1683039600, 'temp': 16, 'feels_like': 13, 'icon': 'skc_d', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 's', 'wind_speed': 2.4,
         'wind_gust': 4.6, 'pressure_mm': 753, 'pressure_pa': 1003, 'humidity': 36, 'uv_index': 1, 'soil_temp': 13,
         'soil_moisture': 0.33, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '19', 'hour_ts': 1683043200, 'temp': 15, 'feels_like': 11, 'icon': 'skc_d', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 's', 'wind_speed': 2.6,
         'wind_gust': 6.5, 'pressure_mm': 753, 'pressure_pa': 1003, 'humidity': 42, 'uv_index': 0, 'soil_temp': 13,
         'soil_moisture': 0.33, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '20', 'hour_ts': 1683046800, 'temp': 13, 'feels_like': 10, 'icon': 'skc_d', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 's', 'wind_speed': 2.3,
         'wind_gust': 6.1, 'pressure_mm': 753, 'pressure_pa': 1003, 'humidity': 48, 'uv_index': 0, 'soil_temp': 13,
         'soil_moisture': 0.33, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '21', 'hour_ts': 1683050400, 'temp': 12, 'feels_like': 9, 'icon': 'skc_n', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 's', 'wind_speed': 2.5,
         'wind_gust': 7.1, 'pressure_mm': 753, 'pressure_pa': 1003, 'humidity': 48, 'uv_index': 0, 'soil_temp': 10,
         'soil_moisture': 0.32, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '22', 'hour_ts': 1683054000, 'temp': 11, 'feels_like': 8, 'icon': 'skc_n', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 's', 'wind_speed': 2.6,
         'wind_gust': 7.3, 'pressure_mm': 753, 'pressure_pa': 1003, 'humidity': 52, 'uv_index': 0, 'soil_temp': 10,
         'soil_moisture': 0.32, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '23', 'hour_ts': 1683057600, 'temp': 10, 'feels_like': 7, 'icon': 'skc_n', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 's', 'wind_speed': 2.7,
         'wind_gust': 7.4, 'pressure_mm': 753, 'pressure_pa': 1003, 'humidity': 55, 'uv_index': 0, 'soil_temp': 10,
         'soil_moisture': 0.32, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0}],
     'biomet': {'index': 0, 'condition': 'magnetic-field_0'}},
    {'date': '2023-05-03', 'date_ts': 1683061200, 'week': 18, 'sunrise': '04:43', 'sunset': '20:09',
     'rise_begin': '03:58', 'set_end': '20:54', 'moon_code': 15, 'moon_text': 'moon-code-15', 'parts': {
        'day_short': {'_source': '6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21', 'temp': 12, 'temp_min': 10,
                      'wind_speed': 4.3, 'wind_gust': 9.6, 'wind_dir': 'sw', 'pressure_mm': 751, 'pressure_pa': 1001,
                      'humidity': 73, 'soil_temp': 10, 'soil_moisture': 0.32, 'prec_mm': 2.4, 'prec_prob': 30,
                      'prec_period': 960, 'cloudness': 1, 'prec_type': 1, 'prec_strength': 0.25, 'icon': 'ovc_-ra',
                      'condition': 'light-rain', 'uv_index': 3, 'feels_like': 8, 'daytime': 'd', 'polar': False,
                      'fresh_snow_mm': 0},
        'evening': {'_source': '18,19,20,21', 'temp_min': 11, 'temp_avg': 12, 'temp_max': 12, 'wind_speed': 2.8,
                    'wind_gust': 7.9, 'wind_dir': 'w', 'pressure_mm': 751, 'pressure_pa': 1001, 'humidity': 80,
                    'soil_temp': 11, 'soil_moisture': 0.33, 'prec_mm': 0.2, 'prec_prob': 20, 'prec_period': 240,
                    'cloudness': 1, 'prec_type': 1, 'prec_strength': 0.25, 'icon': 'ovc_-ra', 'condition': 'light-rain',
                    'uv_index': 0, 'feels_like': 10, 'daytime': 'd', 'polar': False, 'fresh_snow_mm': 0},
        'night': {'_source': '22,23,0,1,2,3,4,5', 'temp_min': 9, 'temp_avg': 10, 'temp_max': 11, 'wind_speed': 3.6,
                  'wind_gust': 8.8, 'wind_dir': 's', 'pressure_mm': 752, 'pressure_pa': 1002, 'humidity': 58,
                  'soil_temp': 8, 'soil_moisture': 0.32, 'prec_mm': 0, 'prec_prob': 0, 'prec_period': 480,
                  'cloudness': 0.25, 'prec_type': 0, 'prec_strength': 0, 'icon': 'skc_n', 'condition': 'partly-cloudy',
                  'uv_index': 0, 'feels_like': 6, 'daytime': 'n', 'polar': False, 'fresh_snow_mm': 0},
        'morning': {'_source': '6,7,8,9,10,11', 'temp_min': 10, 'temp_avg': 11, 'temp_max': 12, 'wind_speed': 4.3,
                    'wind_gust': 9.6, 'wind_dir': 'sw', 'pressure_mm': 750, 'pressure_pa': 999, 'humidity': 61,
                    'soil_temp': 8, 'soil_moisture': 0.32, 'prec_mm': 0.5, 'prec_prob': 20, 'prec_period': 360,
                    'cloudness': 1, 'prec_type': 1, 'prec_strength': 0.25, 'icon': 'ovc_-ra', 'condition': 'light-rain',
                    'uv_index': 3, 'feels_like': 7, 'daytime': 'd', 'polar': False, 'fresh_snow_mm': 0},
        'day': {'_source': '12,13,14,15,16,17', 'temp_min': 11, 'temp_avg': 12, 'temp_max': 12, 'wind_speed': 3.7,
                'wind_gust': 8.8, 'wind_dir': 'sw', 'pressure_mm': 751, 'pressure_pa': 1001, 'humidity': 79,
                'soil_temp': 10, 'soil_moisture': 0.33, 'prec_mm': 1.7, 'prec_prob': 30, 'prec_period': 360,
                'cloudness': 1, 'prec_type': 1, 'prec_strength': 0.25, 'icon': 'ovc_-ra', 'condition': 'light-rain',
                'uv_index': 3, 'feels_like': 9, 'daytime': 'd', 'polar': False, 'fresh_snow_mm': 0},
        'night_short': {'_source': '22,23,0,1,2,3,4,5', 'temp': 9, 'wind_speed': 3.6, 'wind_gust': 8.8, 'wind_dir': 's',
                        'pressure_mm': 752, 'pressure_pa': 1002, 'humidity': 58, 'soil_temp': 8, 'soil_moisture': 0.32,
                        'prec_mm': 0, 'prec_prob': 0, 'prec_period': 480, 'cloudness': 0.25, 'prec_type': 0,
                        'prec_strength': 0, 'icon': 'skc_n', 'condition': 'partly-cloudy', 'uv_index': 0,
                        'feels_like': 6, 'daytime': 'n', 'polar': False, 'fresh_snow_mm': 0}}, 'hours': [
        {'hour': '0', 'hour_ts': 1683061200, 'temp': 10, 'feels_like': 6, 'icon': 'skc_n', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 's', 'wind_speed': 2.8,
         'wind_gust': 7.4, 'pressure_mm': 752, 'pressure_pa': 1002, 'humidity': 56, 'uv_index': 0, 'soil_temp': 8,
         'soil_moisture': 0.32, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '1', 'hour_ts': 1683064800, 'temp': 10, 'feels_like': 6, 'icon': 'skc_n', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 's', 'wind_speed': 2.9,
         'wind_gust': 6.9, 'pressure_mm': 752, 'pressure_pa': 1002, 'humidity': 58, 'uv_index': 0, 'soil_temp': 8,
         'soil_moisture': 0.32, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '2', 'hour_ts': 1683068400, 'temp': 10, 'feels_like': 6, 'icon': 'skc_n', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 's', 'wind_speed': 3.1,
         'wind_gust': 7.9, 'pressure_mm': 752, 'pressure_pa': 1002, 'humidity': 59, 'uv_index': 0, 'soil_temp': 8,
         'soil_moisture': 0.32, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '3', 'hour_ts': 1683072000, 'temp': 9, 'feels_like': 5, 'icon': 'bkn_n', 'condition': 'cloudy',
         'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 's', 'wind_speed': 3.3,
         'wind_gust': 8.6, 'pressure_mm': 751, 'pressure_pa': 1001, 'humidity': 60, 'uv_index': 0, 'soil_temp': 7,
         'soil_moisture': 0.32, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '4', 'hour_ts': 1683075600, 'temp': 9, 'feels_like': 5, 'icon': 'bkn_n', 'condition': 'cloudy',
         'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 's', 'wind_speed': 3.4,
         'wind_gust': 8.5, 'pressure_mm': 751, 'pressure_pa': 1001, 'humidity': 60, 'uv_index': 0, 'soil_temp': 7,
         'soil_moisture': 0.32, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '5', 'hour_ts': 1683079200, 'temp': 9, 'feels_like': 5, 'icon': 'ovc', 'condition': 'overcast',
         'cloudness': 1, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 's', 'wind_speed': 3.6,
         'wind_gust': 8.8, 'pressure_mm': 751, 'pressure_pa': 1001, 'humidity': 61, 'uv_index': 0, 'soil_temp': 7,
         'soil_moisture': 0.32, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '6', 'hour_ts': 1683082800, 'temp': 10, 'feels_like': 5, 'icon': 'ovc', 'condition': 'overcast',
         'cloudness': 1, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 's', 'wind_speed': 3.8,
         'wind_gust': 9.1, 'pressure_mm': 750, 'pressure_pa': 999, 'humidity': 60, 'uv_index': 0, 'soil_temp': 7,
         'soil_moisture': 0.32, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '7', 'hour_ts': 1683086400, 'temp': 11, 'feels_like': 6, 'icon': 'ovc', 'condition': 'overcast',
         'cloudness': 1, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'sw', 'wind_speed': 4.1,
         'wind_gust': 8.2, 'pressure_mm': 750, 'pressure_pa': 999, 'humidity': 59, 'uv_index': 0, 'soil_temp': 7,
         'soil_moisture': 0.32, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '8', 'hour_ts': 1683090000, 'temp': 11, 'feels_like': 7, 'icon': 'ovc', 'condition': 'overcast',
         'cloudness': 1, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'sw', 'wind_speed': 4.3,
         'wind_gust': 8.8, 'pressure_mm': 750, 'pressure_pa': 999, 'humidity': 57, 'uv_index': 1, 'soil_temp': 7,
         'soil_moisture': 0.32, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '9', 'hour_ts': 1683093600, 'temp': 12, 'feels_like': 7, 'icon': 'ovc', 'condition': 'overcast',
         'cloudness': 1, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'sw', 'wind_speed': 4,
         'wind_gust': 9, 'pressure_mm': 750, 'pressure_pa': 999, 'humidity': 60, 'uv_index': 2, 'soil_temp': 9,
         'soil_moisture': 0.32, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '10', 'hour_ts': 1683097200, 'temp': 12, 'feels_like': 8, 'icon': 'ovc_-ra', 'condition': 'light-rain',
         'cloudness': 1, 'prec_type': 1, 'prec_strength': 0.25, 'is_thunder': False, 'wind_dir': 'sw', 'wind_speed': 4,
         'wind_gust': 9.6, 'pressure_mm': 750, 'pressure_pa': 999, 'humidity': 64, 'uv_index': 3, 'soil_temp': 9,
         'soil_moisture': 0.32, 'prec_mm': 0.2, 'prec_period': 60, 'prec_prob': 20},
        {'hour': '11', 'hour_ts': 1683100800, 'temp': 12, 'feels_like': 8, 'icon': 'ovc_-ra', 'condition': 'light-rain',
         'cloudness': 1, 'prec_type': 1, 'prec_strength': 0.25, 'is_thunder': False, 'wind_dir': 'sw',
         'wind_speed': 4.1, 'wind_gust': 8.9, 'pressure_mm': 750, 'pressure_pa': 999, 'humidity': 68, 'uv_index': 3,
         'soil_temp': 9, 'soil_moisture': 0.32, 'prec_mm': 0.3, 'prec_period': 60, 'prec_prob': 20},
        {'hour': '12', 'hour_ts': 1683104400, 'temp': 12, 'feels_like': 9, 'icon': 'ovc_-ra', 'condition': 'light-rain',
         'cloudness': 1, 'prec_type': 1, 'prec_strength': 0.25, 'is_thunder': False, 'wind_dir': 'sw',
         'wind_speed': 3.5, 'wind_gust': 8.7, 'pressure_mm': 750, 'pressure_pa': 999, 'humidity': 73, 'uv_index': 3,
         'soil_temp': 10, 'soil_moisture': 0.32, 'prec_mm': 0.7, 'prec_period': 60, 'prec_prob': 30},
        {'hour': '13', 'hour_ts': 1683108000, 'temp': 11, 'feels_like': 9, 'icon': 'ovc_-ra', 'condition': 'light-rain',
         'cloudness': 1, 'prec_type': 1, 'prec_strength': 0.25, 'is_thunder': False, 'wind_dir': 'sw',
         'wind_speed': 3.7, 'wind_gust': 7.8, 'pressure_mm': 750, 'pressure_pa': 999, 'humidity': 78, 'uv_index': 3,
         'soil_temp': 10, 'soil_moisture': 0.32, 'prec_mm': 0.4, 'prec_period': 60, 'prec_prob': 30},
        {'hour': '14', 'hour_ts': 1683111600, 'temp': 11, 'feels_like': 9, 'icon': 'ovc_-ra', 'condition': 'light-rain',
         'cloudness': 1, 'prec_type': 1, 'prec_strength': 0.25, 'is_thunder': False, 'wind_dir': 'sw',
         'wind_speed': 3.7, 'wind_gust': 8.5, 'pressure_mm': 751, 'pressure_pa': 1001, 'humidity': 79, 'uv_index': 3,
         'soil_temp': 10, 'soil_moisture': 0.32, 'prec_mm': 0.3, 'prec_period': 60, 'prec_prob': 30},
        {'hour': '15', 'hour_ts': 1683115200, 'temp': 11, 'feels_like': 9, 'icon': 'ovc_-ra', 'condition': 'light-rain',
         'cloudness': 1, 'prec_type': 1, 'prec_strength': 0.25, 'is_thunder': False, 'wind_dir': 'sw',
         'wind_speed': 3.2, 'wind_gust': 8.8, 'pressure_mm': 751, 'pressure_pa': 1001, 'humidity': 82, 'uv_index': 2,
         'soil_temp': 10, 'soil_moisture': 0.33, 'prec_mm': 0.1, 'prec_period': 60, 'prec_prob': 30},
        {'hour': '16', 'hour_ts': 1683118800, 'temp': 12, 'feels_like': 9, 'icon': 'ovc_-ra', 'condition': 'light-rain',
         'cloudness': 1, 'prec_type': 1, 'prec_strength': 0.25, 'is_thunder': False, 'wind_dir': 'sw',
         'wind_speed': 3.2, 'wind_gust': 7.9, 'pressure_mm': 751, 'pressure_pa': 1001, 'humidity': 82, 'uv_index': 1,
         'soil_temp': 10, 'soil_moisture': 0.33, 'prec_mm': 0.1, 'prec_period': 60, 'prec_prob': 20},
        {'hour': '17', 'hour_ts': 1683122400, 'temp': 12, 'feels_like': 9, 'icon': 'ovc_-ra', 'condition': 'light-rain',
         'cloudness': 1, 'prec_type': 1, 'prec_strength': 0.25, 'is_thunder': False, 'wind_dir': 'sw',
         'wind_speed': 3.2, 'wind_gust': 7.9, 'pressure_mm': 751, 'pressure_pa': 1001, 'humidity': 78, 'uv_index': 1,
         'soil_temp': 10, 'soil_moisture': 0.33, 'prec_mm': 0.1, 'prec_period': 60, 'prec_prob': 20},
        {'hour': '18', 'hour_ts': 1683126000, 'temp': 12, 'feels_like': 10, 'icon': 'ovc_-ra',
         'condition': 'light-rain', 'cloudness': 1, 'prec_type': 1, 'prec_strength': 0.25, 'is_thunder': False,
         'wind_dir': 'sw', 'wind_speed': 2.8, 'wind_gust': 7.9, 'pressure_mm': 751, 'pressure_pa': 1001, 'humidity': 77,
         'uv_index': 0, 'soil_temp': 11, 'soil_moisture': 0.33, 'prec_mm': 0.1, 'prec_period': 60, 'prec_prob': 20},
        {'hour': '19', 'hour_ts': 1683129600, 'temp': 12, 'feels_like': 10, 'icon': 'ovc', 'condition': 'overcast',
         'cloudness': 1, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'sw', 'wind_speed': 2.2,
         'wind_gust': 4.6, 'pressure_mm': 751, 'pressure_pa': 1001, 'humidity': 79, 'uv_index': 0, 'soil_temp': 11,
         'soil_moisture': 0.33, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '20', 'hour_ts': 1683133200, 'temp': 11, 'feels_like': 10, 'icon': 'ovc_-ra',
         'condition': 'light-rain', 'cloudness': 1, 'prec_type': 1, 'prec_strength': 0.25, 'is_thunder': False,
         'wind_dir': 'sw', 'wind_speed': 2.1, 'wind_gust': 3.6, 'pressure_mm': 751, 'pressure_pa': 1001, 'humidity': 82,
         'uv_index': 0, 'soil_temp': 11, 'soil_moisture': 0.33, 'prec_mm': 0.1, 'prec_period': 60, 'prec_prob': 20},
        {'hour': '21', 'hour_ts': 1683136800, 'temp': 11, 'feels_like': 9, 'icon': 'ovc', 'condition': 'overcast',
         'cloudness': 1, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'w', 'wind_speed': 2.1,
         'wind_gust': 4.7, 'pressure_mm': 752, 'pressure_pa': 1002, 'humidity': 83, 'uv_index': 0, 'soil_temp': 9,
         'soil_moisture': 0.33, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '22', 'hour_ts': 1683140400, 'temp': 11, 'feels_like': 9, 'icon': 'ovc', 'condition': 'overcast',
         'cloudness': 1, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'w', 'wind_speed': 2.1,
         'wind_gust': 3.9, 'pressure_mm': 752, 'pressure_pa': 1002, 'humidity': 80, 'uv_index': 0, 'soil_temp': 9,
         'soil_moisture': 0.33, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '23', 'hour_ts': 1683144000, 'temp': 10, 'feels_like': 8, 'icon': 'ovc', 'condition': 'overcast',
         'cloudness': 1, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'w', 'wind_speed': 2.1,
         'wind_gust': 3, 'pressure_mm': 752, 'pressure_pa': 1002, 'humidity': 79, 'uv_index': 0, 'soil_temp': 9,
         'soil_moisture': 0.33, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0}],
     'biomet': {'index': 1, 'condition': 'magnetic-field_1'}},
    {'date': '2023-05-04', 'date_ts': 1683147600, 'week': 18, 'sunrise': '04:41', 'sunset': '20:11',
     'rise_begin': '03:56', 'set_end': '20:56', 'moon_code': 15, 'moon_text': 'moon-code-15', 'parts': {
        'evening': {'_source': '18,19,20,21', 'temp_min': 11, 'temp_avg': 13, 'temp_max': 15, 'wind_speed': 2.5,
                    'wind_gust': 3.5, 'wind_dir': 'sw', 'pressure_mm': 751, 'pressure_pa': 1001, 'humidity': 49,
                    'soil_temp': 12, 'soil_moisture': 0.31, 'prec_mm': 0, 'prec_prob': 0, 'prec_period': 240,
                    'cloudness': 0.75, 'prec_type': 0, 'prec_strength': 0, 'icon': 'bkn_d', 'condition': 'cloudy',
                    'uv_index': 0, 'feels_like': 10, 'daytime': 'd', 'polar': False, 'fresh_snow_mm': 0},
        'night': {'_source': '22,23,0,1,2,3,4,5', 'temp_min': 4, 'temp_avg': 7, 'temp_max': 11, 'wind_speed': 2.1,
                  'wind_gust': 3.9, 'wind_dir': 'w', 'pressure_mm': 753, 'pressure_pa': 1003, 'humidity': 79,
                  'soil_temp': 8, 'soil_moisture': 0.33, 'prec_mm': 0, 'prec_prob': 0, 'prec_period': 480,
                  'cloudness': 0.25, 'prec_type': 0, 'prec_strength': 0, 'icon': 'skc_n', 'condition': 'partly-cloudy',
                  'uv_index': 0, 'feels_like': 4, 'daytime': 'n', 'polar': False, 'fresh_snow_mm': 0},
        'day_short': {'_source': '6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21', 'temp': 15, 'temp_min': 6,
                      'wind_speed': 2.6, 'wind_gust': 4.4, 'wind_dir': 'w', 'pressure_mm': 753, 'pressure_pa': 1003,
                      'humidity': 48, 'soil_temp': 12, 'soil_moisture': 0.32, 'prec_mm': 0, 'prec_prob': 0,
                      'prec_period': 960, 'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'icon': 'bkn_d',
                      'condition': 'cloudy', 'uv_index': 4, 'feels_like': 9, 'daytime': 'd', 'polar': False,
                      'fresh_snow_mm': 0},
        'morning': {'_source': '6,7,8,9,10,11', 'temp_min': 6, 'temp_avg': 10, 'temp_max': 13, 'wind_speed': 2.3,
                    'wind_gust': 4, 'wind_dir': 'nw', 'pressure_mm': 754, 'pressure_pa': 1005, 'humidity': 61,
                    'soil_temp': 6, 'soil_moisture': 0.33, 'prec_mm': 0, 'prec_prob': 0, 'prec_period': 360,
                    'cloudness': 0.25, 'prec_type': 0, 'prec_strength': 0, 'icon': 'skc_d',
                    'condition': 'partly-cloudy', 'uv_index': 4, 'feels_like': 8, 'daytime': 'd', 'polar': False,
                    'fresh_snow_mm': 0},
        'day': {'_source': '12,13,14,15,16,17', 'temp_min': 13, 'temp_avg': 14, 'temp_max': 15, 'wind_speed': 2.6,
                'wind_gust': 4.4, 'wind_dir': 'sw', 'pressure_mm': 752, 'pressure_pa': 1002, 'humidity': 34,
                'soil_temp': 13, 'soil_moisture': 0.32, 'prec_mm': 0, 'prec_prob': 0, 'prec_period': 360,
                'cloudness': 0.75, 'prec_type': 0, 'prec_strength': 0, 'icon': 'bkn_d', 'condition': 'cloudy',
                'uv_index': 4, 'feels_like': 11, 'daytime': 'd', 'polar': False, 'fresh_snow_mm': 0},
        'night_short': {'_source': '22,23,0,1,2,3,4,5', 'temp': 4, 'wind_speed': 2.1, 'wind_gust': 3.9, 'wind_dir': 'w',
                        'pressure_mm': 753, 'pressure_pa': 1003, 'humidity': 79, 'soil_temp': 8, 'soil_moisture': 0.33,
                        'prec_mm': 0, 'prec_prob': 0, 'prec_period': 480, 'cloudness': 0.25, 'prec_type': 0,
                        'prec_strength': 0, 'icon': 'skc_n', 'condition': 'partly-cloudy', 'uv_index': 0,
                        'feels_like': 4, 'daytime': 'n', 'polar': False, 'fresh_snow_mm': 0}}, 'hours': [
        {'hour': '0', 'hour_ts': 1683147600, 'temp': 9, 'feels_like': 7, 'icon': 'bkn_n', 'condition': 'cloudy',
         'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'w', 'wind_speed': 1.7,
         'wind_gust': 3.5, 'pressure_mm': 752, 'pressure_pa': 1002, 'humidity': 81, 'uv_index': 0, 'soil_temp': 8,
         'soil_moisture': 0.33, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '1', 'hour_ts': 1683151200, 'temp': 8, 'feels_like': 6, 'icon': 'skc_n', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'w', 'wind_speed': 1.6,
         'wind_gust': 3.4, 'pressure_mm': 753, 'pressure_pa': 1003, 'humidity': 81, 'uv_index': 0, 'soil_temp': 8,
         'soil_moisture': 0.33, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '2', 'hour_ts': 1683154800, 'temp': 6, 'feels_like': 4, 'icon': 'skc_n', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'nw', 'wind_speed': 1.8,
         'wind_gust': 3.4, 'pressure_mm': 753, 'pressure_pa': 1003, 'humidity': 79, 'uv_index': 0, 'soil_temp': 8,
         'soil_moisture': 0.33, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '3', 'hour_ts': 1683158400, 'temp': 5, 'feels_like': 2, 'icon': 'skc_n', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'w', 'wind_speed': 1.8,
         'wind_gust': 3.2, 'pressure_mm': 753, 'pressure_pa': 1003, 'humidity': 75, 'uv_index': 0, 'soil_temp': 5,
         'soil_moisture': 0.33, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '4', 'hour_ts': 1683162000, 'temp': 4, 'feels_like': 1, 'icon': 'skc_n', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'w', 'wind_speed': 1.8,
         'wind_gust': 3.1, 'pressure_mm': 753, 'pressure_pa': 1003, 'humidity': 79, 'uv_index': 0, 'soil_temp': 5,
         'soil_moisture': 0.33, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '5', 'hour_ts': 1683165600, 'temp': 5, 'feels_like': 1, 'icon': 'skc_d', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'w', 'wind_speed': 1.9,
         'wind_gust': 3, 'pressure_mm': 753, 'pressure_pa': 1003, 'humidity': 79, 'uv_index': 0, 'soil_temp': 5,
         'soil_moisture': 0.33, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '6', 'hour_ts': 1683169200, 'temp': 6, 'feels_like': 2, 'icon': 'skc_d', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'nw', 'wind_speed': 2,
         'wind_gust': 3.8, 'pressure_mm': 754, 'pressure_pa': 1005, 'humidity': 76, 'uv_index': 0, 'soil_temp': 4,
         'soil_moisture': 0.33, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '7', 'hour_ts': 1683172800, 'temp': 7, 'feels_like': 4, 'icon': 'skc_d', 'condition': 'clear',
         'cloudness': 0, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'nw', 'wind_speed': 2.2,
         'wind_gust': 4, 'pressure_mm': 754, 'pressure_pa': 1005, 'humidity': 72, 'uv_index': 0, 'soil_temp': 4,
         'soil_moisture': 0.33, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '8', 'hour_ts': 1683176400, 'temp': 9, 'feels_like': 6, 'icon': 'bkn_d', 'condition': 'cloudy',
         'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'nw', 'wind_speed': 2.3,
         'wind_gust': 3.8, 'pressure_mm': 754, 'pressure_pa': 1005, 'humidity': 65, 'uv_index': 1, 'soil_temp': 4,
         'soil_moisture': 0.33, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '9', 'hour_ts': 1683180000, 'temp': 11, 'feels_like': 8, 'icon': 'bkn_d', 'condition': 'cloudy',
         'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'nw', 'wind_speed': 1.8,
         'wind_gust': 3.7, 'pressure_mm': 754, 'pressure_pa': 1005, 'humidity': 59, 'uv_index': 2, 'soil_temp': 9,
         'soil_moisture': 0.33, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '10', 'hour_ts': 1683183600, 'temp': 12, 'feels_like': 9, 'icon': 'bkn_d', 'condition': 'cloudy',
         'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'w', 'wind_speed': 2.1,
         'wind_gust': 3.5, 'pressure_mm': 754, 'pressure_pa': 1005, 'humidity': 48, 'uv_index': 3, 'soil_temp': 9,
         'soil_moisture': 0.33, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '11', 'hour_ts': 1683187200, 'temp': 13, 'feels_like': 10, 'icon': 'bkn_d', 'condition': 'cloudy',
         'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'w', 'wind_speed': 2.3,
         'wind_gust': 3.7, 'pressure_mm': 753, 'pressure_pa': 1003, 'humidity': 45, 'uv_index': 4, 'soil_temp': 9,
         'soil_moisture': 0.33, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '12', 'hour_ts': 1683190800, 'temp': 13, 'feels_like': 11, 'icon': 'bkn_d', 'condition': 'cloudy',
         'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'w', 'wind_speed': 2.1,
         'wind_gust': 3.9, 'pressure_mm': 753, 'pressure_pa': 1003, 'humidity': 39, 'uv_index': 4, 'soil_temp': 13,
         'soil_moisture': 0.32, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '13', 'hour_ts': 1683194400, 'temp': 14, 'feels_like': 11, 'icon': 'bkn_d', 'condition': 'cloudy',
         'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'sw', 'wind_speed': 2.4,
         'wind_gust': 4.1, 'pressure_mm': 753, 'pressure_pa': 1003, 'humidity': 35, 'uv_index': 4, 'soil_temp': 13,
         'soil_moisture': 0.32, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '14', 'hour_ts': 1683198000, 'temp': 14, 'feels_like': 11, 'icon': 'bkn_d', 'condition': 'cloudy',
         'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'sw', 'wind_speed': 2.6,
         'wind_gust': 4.4, 'pressure_mm': 753, 'pressure_pa': 1003, 'humidity': 33, 'uv_index': 3, 'soil_temp': 13,
         'soil_moisture': 0.32, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '15', 'hour_ts': 1683201600, 'temp': 15, 'feels_like': 11, 'icon': 'ovc', 'condition': 'overcast',
         'cloudness': 1, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'sw', 'wind_speed': 2.3,
         'wind_gust': 4, 'pressure_mm': 752, 'pressure_pa': 1002, 'humidity': 34, 'uv_index': 3, 'soil_temp': 14,
         'soil_moisture': 0.32, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '16', 'hour_ts': 1683205200, 'temp': 15, 'feels_like': 11, 'icon': 'ovc', 'condition': 'overcast',
         'cloudness': 1, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'sw', 'wind_speed': 2.6,
         'wind_gust': 4.1, 'pressure_mm': 752, 'pressure_pa': 1002, 'humidity': 33, 'uv_index': 2, 'soil_temp': 14,
         'soil_moisture': 0.32, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '17', 'hour_ts': 1683208800, 'temp': 15, 'feels_like': 11, 'icon': 'ovc', 'condition': 'overcast',
         'cloudness': 1, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'w', 'wind_speed': 2.6,
         'wind_gust': 4, 'pressure_mm': 751, 'pressure_pa': 1001, 'humidity': 32, 'uv_index': 1, 'soil_temp': 14,
         'soil_moisture': 0.32, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '18', 'hour_ts': 1683212400, 'temp': 15, 'feels_like': 11, 'icon': 'ovc', 'condition': 'overcast',
         'cloudness': 1, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'w', 'wind_speed': 2.5,
         'wind_gust': 3.5, 'pressure_mm': 751, 'pressure_pa': 1001, 'humidity': 40, 'uv_index': 0, 'soil_temp': 12,
         'soil_moisture': 0.31, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '19', 'hour_ts': 1683216000, 'temp': 14, 'feels_like': 11, 'icon': 'ovc', 'condition': 'overcast',
         'cloudness': 1, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'w', 'wind_speed': 2,
         'wind_gust': 2.4, 'pressure_mm': 751, 'pressure_pa': 1001, 'humidity': 46, 'uv_index': 0, 'soil_temp': 12,
         'soil_moisture': 0.31, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '20', 'hour_ts': 1683219600, 'temp': 12, 'feels_like': 10, 'icon': 'bkn_d', 'condition': 'cloudy',
         'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'sw', 'wind_speed': 1.8,
         'wind_gust': 2.5, 'pressure_mm': 751, 'pressure_pa': 1001, 'humidity': 52, 'uv_index': 0, 'soil_temp': 12,
         'soil_moisture': 0.31, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '21', 'hour_ts': 1683223200, 'temp': 11, 'feels_like': 8, 'icon': 'bkn_n', 'condition': 'cloudy',
         'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'sw', 'wind_speed': 1.7,
         'wind_gust': 2.2, 'pressure_mm': 751, 'pressure_pa': 1001, 'humidity': 57, 'uv_index': 0, 'soil_temp': 9,
         'soil_moisture': 0.31, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '22', 'hour_ts': 1683226800, 'temp': 10, 'feels_like': 7, 'icon': 'bkn_n', 'condition': 'cloudy',
         'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'sw', 'wind_speed': 1.7,
         'wind_gust': 2.2, 'pressure_mm': 751, 'pressure_pa': 1001, 'humidity': 59, 'uv_index': 0, 'soil_temp': 9,
         'soil_moisture': 0.31, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '23', 'hour_ts': 1683230400, 'temp': 9, 'feels_like': 6, 'icon': 'bkn_n', 'condition': 'cloudy',
         'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'sw', 'wind_speed': 1.9,
         'wind_gust': 2.9, 'pressure_mm': 751, 'pressure_pa': 1001, 'humidity': 59, 'uv_index': 0, 'soil_temp': 9,
         'soil_moisture': 0.31, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0}],
     'biomet': {'index': 0, 'condition': 'magnetic-field_0'}},
    {'date': '2023-05-05', 'date_ts': 1683234000, 'week': 18, 'sunrise': '04:38', 'sunset': '20:13',
     'rise_begin': '03:53', 'set_end': '20:58', 'moon_code': 0, 'moon_text': 'moon-code-0', 'parts': {
        'night_short': {'_source': '22,23,0,1,2,3,4,5', 'temp': 5, 'wind_speed': 2.1, 'wind_gust': 4.4,
                        'wind_dir': 'nw', 'pressure_mm': 751, 'pressure_pa': 1001, 'humidity': 68, 'soil_temp': 7,
                        'soil_moisture': 0.31, 'prec_mm': 0, 'prec_prob': 0, 'prec_period': 480, 'cloudness': 0.5,
                        'prec_type': 0, 'prec_strength': 0, 'icon': 'bkn_n', 'condition': 'cloudy', 'uv_index': 0,
                        'feels_like': 4, 'daytime': 'n', 'polar': False, 'fresh_snow_mm': 0},
        'morning': {'_source': '6,7,8,9,10,11', 'temp_min': 6, 'temp_avg': 9, 'temp_max': 11, 'wind_speed': 3.2,
                    'wind_gust': 7.2, 'wind_dir': 'nw', 'pressure_mm': 750, 'pressure_pa': 999, 'humidity': 64,
                    'soil_temp': 7, 'soil_moisture': 0.31, 'prec_mm': 0, 'prec_prob': 0, 'prec_period': 360,
                    'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'icon': 'bkn_d', 'condition': 'cloudy',
                    'uv_index': 2, 'feels_like': 5, 'daytime': 'd', 'polar': False, 'fresh_snow_mm': 0},
        'evening': {'_source': '18,19,21', 'temp_min': 8, 'temp_avg': 9, 'temp_max': 10, 'wind_speed': 3.4,
                    'wind_gust': 8.3, 'wind_dir': 'n', 'pressure_mm': 748, 'pressure_pa': 997, 'humidity': 61,
                    'soil_temp': 11, 'soil_moisture': 0.31, 'prec_mm': 0.3, 'prec_prob': 20, 'prec_period': 240,
                    'cloudness': 1, 'prec_type': 1, 'prec_strength': 0.25, 'icon': 'ovc_-ra', 'condition': 'light-rain',
                    'uv_index': 0, 'feels_like': 5, 'daytime': 'd', 'polar': False, 'fresh_snow_mm': 0},
        'day_short': {'_source': '6,7,8,9,10,11,12,13,14,15,16,17,18,19,21', 'temp': 12, 'temp_min': 6,
                      'wind_speed': 3.8, 'wind_gust': 8.6, 'wind_dir': 'n', 'pressure_mm': 749, 'pressure_pa': 998,
                      'humidity': 58, 'soil_temp': 11, 'soil_moisture': 0.31, 'prec_mm': 0.3, 'prec_prob': 20,
                      'prec_period': 960, 'cloudness': 0.75, 'prec_type': 1, 'prec_strength': 0.25, 'icon': 'bkn_-ra_d',
                      'condition': 'light-rain', 'uv_index': 2, 'feels_like': 6, 'daytime': 'd', 'polar': False,
                      'fresh_snow_mm': 0},
        'night': {'_source': '22,23,0,1,2,3,4,5', 'temp_min': 5, 'temp_avg': 7, 'temp_max': 10, 'wind_speed': 2.1,
                  'wind_gust': 4.4, 'wind_dir': 'nw', 'pressure_mm': 751, 'pressure_pa': 1001, 'humidity': 68,
                  'soil_temp': 7, 'soil_moisture': 0.31, 'prec_mm': 0, 'prec_prob': 0, 'prec_period': 480,
                  'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'icon': 'bkn_n', 'condition': 'cloudy',
                  'uv_index': 0, 'feels_like': 4, 'daytime': 'n', 'polar': False, 'fresh_snow_mm': 0},
        'day': {'_source': '12,13,14,15,16,17', 'temp_min': 11, 'temp_avg': 11, 'temp_max': 12, 'wind_speed': 3.8,
                'wind_gust': 8.6, 'wind_dir': 'nw', 'pressure_mm': 749, 'pressure_pa': 998, 'humidity': 50,
                'soil_temp': 12, 'soil_moisture': 0.31, 'prec_mm': 0, 'prec_prob': 0, 'prec_period': 360,
                'cloudness': 1, 'prec_type': 0, 'prec_strength': 0, 'icon': 'ovc', 'condition': 'overcast',
                'uv_index': 2, 'feels_like': 7, 'daytime': 'd', 'polar': False, 'fresh_snow_mm': 0}}, 'hours': [
        {'hour': '0', 'hour_ts': 1683234000, 'temp': 8, 'feels_like': 5, 'icon': 'bkn_n', 'condition': 'cloudy',
         'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'nw', 'wind_speed': 1.8,
         'wind_gust': 3.2, 'pressure_mm': 751, 'pressure_pa': 1001, 'humidity': 66, 'uv_index': 0, 'soil_temp': 7,
         'soil_moisture': 0.31, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '1', 'hour_ts': 1683237600, 'temp': 7, 'feels_like': 4, 'icon': 'bkn_n', 'condition': 'cloudy',
         'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'nw', 'wind_speed': 2.1,
         'wind_gust': 4.3, 'pressure_mm': 751, 'pressure_pa': 1001, 'humidity': 66, 'uv_index': 0, 'soil_temp': 7,
         'soil_moisture': 0.31, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '2', 'hour_ts': 1683241200, 'temp': 7, 'feels_like': 4, 'icon': 'bkn_n', 'condition': 'cloudy',
         'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'nw', 'wind_speed': 2,
         'wind_gust': 4.1, 'pressure_mm': 751, 'pressure_pa': 1001, 'humidity': 70, 'uv_index': 0, 'soil_temp': 7,
         'soil_moisture': 0.31, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '3', 'hour_ts': 1683244800, 'temp': 6, 'feels_like': 3, 'icon': 'ovc', 'condition': 'overcast',
         'cloudness': 1, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'nw', 'wind_speed': 1.8,
         'wind_gust': 3.3, 'pressure_mm': 750, 'pressure_pa': 999, 'humidity': 73, 'uv_index': 0, 'soil_temp': 6,
         'soil_moisture': 0.31, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '4', 'hour_ts': 1683248400, 'temp': 5, 'feels_like': 2, 'icon': 'bkn_n', 'condition': 'cloudy',
         'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'nw', 'wind_speed': 1.9,
         'wind_gust': 3.5, 'pressure_mm': 750, 'pressure_pa': 999, 'humidity': 75, 'uv_index': 0, 'soil_temp': 6,
         'soil_moisture': 0.31, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '5', 'hour_ts': 1683252000, 'temp': 5, 'feels_like': 2, 'icon': 'bkn_d', 'condition': 'cloudy',
         'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'nw', 'wind_speed': 2,
         'wind_gust': 4.4, 'pressure_mm': 750, 'pressure_pa': 999, 'humidity': 76, 'uv_index': 0, 'soil_temp': 6,
         'soil_moisture': 0.31, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '6', 'hour_ts': 1683255600, 'temp': 6, 'feels_like': 2, 'icon': 'bkn_d', 'condition': 'cloudy',
         'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'nw', 'wind_speed': 2.2,
         'wind_gust': 5, 'pressure_mm': 750, 'pressure_pa': 999, 'humidity': 76, 'uv_index': 0, 'soil_temp': 5,
         'soil_moisture': 0.31, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '7', 'hour_ts': 1683259200, 'temp': 7, 'feels_like': 4, 'icon': 'bkn_d', 'condition': 'cloudy',
         'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'nw', 'wind_speed': 2.5,
         'wind_gust': 5.6, 'pressure_mm': 750, 'pressure_pa': 999, 'humidity': 71, 'uv_index': 0, 'soil_temp': 5,
         'soil_moisture': 0.31, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '8', 'hour_ts': 1683262800, 'temp': 8, 'feels_like': 5, 'icon': 'bkn_d', 'condition': 'cloudy',
         'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'nw', 'wind_speed': 2.8,
         'wind_gust': 6.4, 'pressure_mm': 750, 'pressure_pa': 999, 'humidity': 67, 'uv_index': 1, 'soil_temp': 5,
         'soil_moisture': 0.31, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '9', 'hour_ts': 1683266400, 'temp': 9, 'feels_like': 6, 'icon': 'bkn_d', 'condition': 'cloudy',
         'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'w', 'wind_speed': 2.8,
         'wind_gust': 6.8, 'pressure_mm': 749, 'pressure_pa': 998, 'humidity': 62, 'uv_index': 2, 'soil_temp': 9,
         'soil_moisture': 0.32, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '10', 'hour_ts': 1683270000, 'temp': 10, 'feels_like': 7, 'icon': 'bkn_d', 'condition': 'cloudy',
         'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'w', 'wind_speed': 3,
         'wind_gust': 7.2, 'pressure_mm': 749, 'pressure_pa': 998, 'humidity': 57, 'uv_index': 1, 'soil_temp': 9,
         'soil_moisture': 0.32, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '11', 'hour_ts': 1683273600, 'temp': 11, 'feels_like': 7, 'icon': 'ovc', 'condition': 'overcast',
         'cloudness': 1, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'nw', 'wind_speed': 3.2,
         'wind_gust': 7.1, 'pressure_mm': 749, 'pressure_pa': 998, 'humidity': 50, 'uv_index': 1, 'soil_temp': 9,
         'soil_moisture': 0.32, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '12', 'hour_ts': 1683277200, 'temp': 11, 'feels_like': 7, 'icon': 'ovc', 'condition': 'overcast',
         'cloudness': 1, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'nw', 'wind_speed': 3.1,
         'wind_gust': 6.7, 'pressure_mm': 749, 'pressure_pa': 998, 'humidity': 47, 'uv_index': 2, 'soil_temp': 12,
         'soil_moisture': 0.32, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '13', 'hour_ts': 1683280800, 'temp': 12, 'feels_like': 7, 'icon': 'ovc', 'condition': 'overcast',
         'cloudness': 1, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'nw', 'wind_speed': 3.2,
         'wind_gust': 6.6, 'pressure_mm': 749, 'pressure_pa': 998, 'humidity': 47, 'uv_index': 1, 'soil_temp': 12,
         'soil_moisture': 0.32, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '14', 'hour_ts': 1683284400, 'temp': 11, 'feels_like': 8, 'icon': 'ovc', 'condition': 'overcast',
         'cloudness': 1, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'nw', 'wind_speed': 3,
         'wind_gust': 6, 'pressure_mm': 748, 'pressure_pa': 997, 'humidity': 50, 'uv_index': 1, 'soil_temp': 12,
         'soil_moisture': 0.32, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '15', 'hour_ts': 1683288000, 'temp': 11, 'feels_like': 7, 'icon': 'bkn_d', 'condition': 'cloudy',
         'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'nw', 'wind_speed': 3.6,
         'wind_gust': 8.6, 'pressure_mm': 749, 'pressure_pa': 998, 'humidity': 52, 'uv_index': 1, 'soil_temp': 12,
         'soil_moisture': 0.31, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '16', 'hour_ts': 1683291600, 'temp': 11, 'feels_like': 6, 'icon': 'ovc', 'condition': 'overcast',
         'cloudness': 1, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'nw', 'wind_speed': 3.7,
         'wind_gust': 8, 'pressure_mm': 748, 'pressure_pa': 997, 'humidity': 51, 'uv_index': 1, 'soil_temp': 12,
         'soil_moisture': 0.31, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '17', 'hour_ts': 1683295200, 'temp': 11, 'feels_like': 6, 'icon': 'ovc', 'condition': 'overcast',
         'cloudness': 1, 'prec_type': 0, 'prec_strength': 0, 'is_thunder': False, 'wind_dir': 'nw', 'wind_speed': 3.8,
         'wind_gust': 8.1, 'pressure_mm': 748, 'pressure_pa': 997, 'humidity': 50, 'uv_index': 0, 'soil_temp': 12,
         'soil_moisture': 0.31, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
        {'hour': '18', 'hour_ts': 1683298800, 'temp': 10, 'feels_like': 6, 'icon': 'ovc_-ra', 'condition': 'light-rain',
         'cloudness': 1, 'prec_type': 1, 'prec_strength': 0.25, 'is_thunder': False, 'wind_dir': 'nw',
         'wind_speed': 3.4, 'wind_gust': 8.3, 'pressure_mm': 748, 'pressure_pa': 997, 'humidity': 55, 'uv_index': 0,
         'soil_temp': 11, 'soil_moisture': 0.31, 'prec_mm': 0.2, 'prec_period': 60, 'prec_prob': 20},
        {'hour': '19', 'hour_ts': 1683302400, 'temp': 9, 'feels_like': 5, 'icon': 'ovc_-ra', 'condition': 'light-rain',
         'cloudness': 1, 'prec_type': 1, 'prec_strength': 0.25, 'is_thunder': False, 'wind_dir': 'n', 'wind_speed': 3.2,
         'wind_gust': 6.3, 'pressure_mm': 748, 'pressure_pa': 997, 'humidity': 61, 'uv_index': 0, 'soil_temp': 11,
         'soil_moisture': 0.31, 'prec_mm': 0.1, 'prec_period': 60, 'prec_prob': 20}],
     'biomet': {'index': 0, 'condition': 'magnetic-field_0'}},
    {'date': '2023-05-06', 'date_ts': 1683320400, 'week': 18, 'sunrise': '04:36', 'sunset': '20:15',
     'rise_begin': '03:51', 'set_end': '21:01', 'moon_code': 0, 'moon_text': 'moon-code-0', 'parts': {
        'night_short': {'_source': '0,3', 'temp': 3, 'wind_speed': 3.5, 'wind_gust': 8.1, 'wind_dir': 'nw',
                        'pressure_mm': 748, 'pressure_pa': 997, 'humidity': 77, 'soil_temp': 5, 'soil_moisture': 0.32,
                        'prec_mm': 0.6, 'prec_prob': 20, 'prec_period': 360, 'cloudness': 0.75, 'prec_type': 1,
                        'prec_strength': 0.25, 'icon': 'bkn_-ra_n', 'condition': 'light-rain', 'uv_index': 0,
                        'feels_like': 0, 'daytime': 'n', 'polar': False, 'fresh_snow_mm': 0},
        'day_short': {'_source': '6,9,12,15,18,21', 'temp': 7, 'temp_min': 2, 'wind_speed': 5.7, 'wind_gust': 12.3,
                      'wind_dir': 'nw', 'pressure_mm': 749, 'pressure_pa': 998, 'humidity': 66, 'soil_temp': 6,
                      'soil_moisture': 0.35, 'prec_mm': 0, 'prec_prob': 0, 'prec_period': 1080, 'cloudness': 1,
                      'prec_type': 0, 'prec_strength': 0, 'icon': 'ovc', 'condition': 'overcast', 'uv_index': 0,
                      'feels_like': -1, 'daytime': 'd', 'polar': False, 'fresh_snow_mm': 0},
        'night': {'_source': '0,3', 'temp_min': 3, 'temp_avg': 4, 'temp_max': 5, 'wind_speed': 3.5, 'wind_gust': 8.1,
                  'wind_dir': 'nw', 'pressure_mm': 748, 'pressure_pa': 997, 'humidity': 77, 'soil_temp': 5,
                  'soil_moisture': 0.32, 'prec_mm': 0.6, 'prec_prob': 20, 'prec_period': 360, 'cloudness': 0.75,
                  'prec_type': 1, 'prec_strength': 0.25, 'icon': 'bkn_-ra_n', 'condition': 'light-rain', 'uv_index': 0,
                  'feels_like': 0, 'daytime': 'n', 'polar': False, 'fresh_snow_mm': 0},
        'evening': {'_source': '18,21', 'temp_min': 4, 'temp_avg': 5, 'temp_max': 6, 'wind_speed': 4.8,
                    'wind_gust': 9.7, 'wind_dir': 'nw', 'pressure_mm': 750, 'pressure_pa': 999, 'humidity': 67,
                    'soil_temp': 6, 'soil_moisture': 0.35, 'prec_mm': 0, 'prec_prob': 0, 'prec_period': 360,
                    'cloudness': 0.75, 'prec_type': 0, 'prec_strength': 0, 'icon': 'bkn_d', 'condition': 'cloudy',
                    'feels_like': 0, 'daytime': 'd', 'polar': False, 'fresh_snow_mm': 0},
        'day': {'_source': '12,15', 'temp_min': 6, 'temp_avg': 7, 'temp_max': 7, 'wind_speed': 5.7, 'wind_gust': 12.2,
                'wind_dir': 'w', 'pressure_mm': 748, 'pressure_pa': 997, 'humidity': 56, 'soil_temp': 8,
                'soil_moisture': 0.35, 'prec_mm': 0, 'prec_prob': 0, 'prec_period': 360, 'cloudness': 1, 'prec_type': 0,
                'prec_strength': 0, 'icon': 'ovc', 'condition': 'overcast', 'uv_index': 0, 'feels_like': 1,
                'daytime': 'd', 'polar': False, 'fresh_snow_mm': 0},
        'morning': {'_source': '6,9', 'temp_min': 2, 'temp_avg': 3, 'temp_max': 4, 'wind_speed': 4.8, 'wind_gust': 12.3,
                    'wind_dir': 'nw', 'pressure_mm': 748, 'pressure_pa': 997, 'humidity': 75, 'soil_temp': 4,
                    'soil_moisture': 0.35, 'prec_mm': 0, 'prec_prob': 0, 'prec_period': 360, 'cloudness': 1,
                    'prec_type': 0, 'prec_strength': 0, 'icon': 'ovc', 'condition': 'overcast', 'uv_index': 0,
                    'feels_like': -2, 'daytime': 'd', 'polar': False, 'fresh_snow_mm': 0}}, 'hours': []},
    {'date': '2023-05-07', 'date_ts': 1683406800, 'week': 18, 'sunrise': '04:34', 'sunset': '20:17',
     'rise_begin': '03:48', 'set_end': '21:03', 'moon_code': 1, 'moon_text': 'moon-code-1', 'parts': {
        'night_short': {'_source': '0,3', 'temp': 2, 'wind_speed': 4, 'wind_gust': 8.2, 'wind_dir': 'nw',
                        'pressure_mm': 751, 'pressure_pa': 1001, 'humidity': 78, 'soil_temp': 3, 'soil_moisture': 0.34,
                        'prec_mm': 0, 'prec_prob': 0, 'prec_period': 360, 'cloudness': 1, 'prec_type': 0,
                        'prec_strength': 0, 'icon': 'ovc', 'condition': 'overcast', 'feels_like': -2, 'daytime': 'n',
                        'polar': False, 'fresh_snow_mm': 0},
        'day_short': {'_source': '6,9,12,15,18,21', 'temp': 9, 'temp_min': 2, 'wind_speed': 4.9, 'wind_gust': 10.1,
                      'wind_dir': 'nw', 'pressure_mm': 753, 'pressure_pa': 1003, 'humidity': 56, 'soil_temp': 6,
                      'soil_moisture': 0.34, 'prec_mm': 0, 'prec_prob': 0, 'prec_period': 1080, 'cloudness': 0.5,
                      'prec_type': 0, 'prec_strength': 0, 'icon': 'bkn_d', 'condition': 'cloudy', 'feels_like': 1,
                      'daytime': 'd', 'polar': False, 'fresh_snow_mm': 0},
        'morning': {'_source': '6,9', 'temp_min': 2, 'temp_avg': 3, 'temp_max': 4, 'wind_speed': 4.5, 'wind_gust': 10.1,
                    'wind_dir': 'nw', 'pressure_mm': 752, 'pressure_pa': 1002, 'humidity': 75, 'soil_temp': 3,
                    'soil_moisture': 0.34, 'prec_mm': 0, 'prec_prob': 0, 'prec_period': 360, 'cloudness': 0.75,
                    'prec_type': 0, 'prec_strength': 0, 'icon': 'bkn_d', 'condition': 'cloudy', 'feels_like': -2,
                    'daytime': 'd', 'polar': False, 'fresh_snow_mm': 0},
        'day': {'_source': '12,15', 'temp_min': 8, 'temp_avg': 9, 'temp_max': 9, 'wind_speed': 4.9, 'wind_gust': 9.9,
                'wind_dir': 'nw', 'pressure_mm': 753, 'pressure_pa': 1003, 'humidity': 46, 'soil_temp': 7,
                'soil_moisture': 0.34, 'prec_mm': 0, 'prec_prob': 0, 'prec_period': 360, 'cloudness': 0.5,
                'prec_type': 0, 'prec_strength': 0, 'icon': 'bkn_d', 'condition': 'cloudy', 'feels_like': 3,
                'daytime': 'd', 'polar': False, 'fresh_snow_mm': 0},
        'evening': {'_source': '18,21', 'temp_min': 8, 'temp_avg': 9, 'temp_max': 9, 'wind_speed': 3.5,
                    'wind_gust': 7.1, 'wind_dir': 'nw', 'pressure_mm': 755, 'pressure_pa': 1006, 'humidity': 46,
                    'soil_temp': 7, 'soil_moisture': 0.35, 'prec_mm': 0, 'prec_prob': 0, 'prec_period': 360,
                    'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'icon': 'bkn_d', 'condition': 'cloudy',
                    'feels_like': 4, 'daytime': 'd', 'polar': False, 'fresh_snow_mm': 0},
        'night': {'_source': '0,3', 'temp_min': 2, 'temp_avg': 3, 'temp_max': 3, 'wind_speed': 4, 'wind_gust': 8.2,
                  'wind_dir': 'nw', 'pressure_mm': 751, 'pressure_pa': 1001, 'humidity': 78, 'soil_temp': 3,
                  'soil_moisture': 0.34, 'prec_mm': 0, 'prec_prob': 0, 'prec_period': 360, 'cloudness': 1,
                  'prec_type': 0, 'prec_strength': 0, 'icon': 'ovc', 'condition': 'overcast', 'feels_like': -2,
                  'daytime': 'n', 'polar': False, 'fresh_snow_mm': 0}}, 'hours': []},
    {'date': '2023-05-08', 'date_ts': 1683493200, 'week': 19, 'sunrise': '04:32', 'sunset': '20:19',
     'rise_begin': '03:46', 'set_end': '21:05', 'moon_code': 1, 'moon_text': 'moon-code-1', 'parts': {
        'night_short': {'_source': '0,3', 'temp': 3, 'wind_speed': 2.4, 'wind_gust': 5.3, 'wind_dir': 'nw',
                        'pressure_mm': 756, 'pressure_pa': 1007, 'humidity': 70, 'soil_temp': 3, 'soil_moisture': 0.34,
                        'prec_mm': 0, 'prec_prob': 0, 'prec_period': 360, 'cloudness': 0.5, 'prec_type': 0,
                        'prec_strength': 0, 'icon': 'bkn_n', 'condition': 'cloudy', 'feels_like': 0, 'daytime': 'n',
                        'polar': False, 'fresh_snow_mm': 0},
        'night': {'_source': '0,3', 'temp_min': 3, 'temp_avg': 4, 'temp_max': 5, 'wind_speed': 2.4, 'wind_gust': 5.3,
                  'wind_dir': 'nw', 'pressure_mm': 756, 'pressure_pa': 1007, 'humidity': 70, 'soil_temp': 3,
                  'soil_moisture': 0.34, 'prec_mm': 0, 'prec_prob': 0, 'prec_period': 360, 'cloudness': 0.5,
                  'prec_type': 0, 'prec_strength': 0, 'icon': 'bkn_n', 'condition': 'cloudy', 'feels_like': 0,
                  'daytime': 'n', 'polar': False, 'fresh_snow_mm': 0},
        'day': {'_source': '12,15', 'temp_min': 10, 'temp_avg': 11, 'temp_max': 12, 'wind_speed': 3.5, 'wind_gust': 7.3,
                'wind_dir': 'nw', 'pressure_mm': 756, 'pressure_pa': 1007, 'humidity': 40, 'soil_temp': 7,
                'soil_moisture': 0.34, 'prec_mm': 0, 'prec_prob': 0, 'prec_period': 360, 'cloudness': 0.5,
                'prec_type': 0, 'prec_strength': 0, 'icon': 'bkn_d', 'condition': 'cloudy', 'feels_like': 6,
                'daytime': 'd', 'polar': False, 'fresh_snow_mm': 0},
        'evening': {'_source': '18,21', 'temp_min': 9, 'temp_avg': 11, 'temp_max': 12, 'wind_speed': 3.1,
                    'wind_gust': 7.3, 'wind_dir': 'w', 'pressure_mm': 755, 'pressure_pa': 1006, 'humidity': 47,
                    'soil_temp': 7, 'soil_moisture': 0.34, 'prec_mm': 0, 'prec_prob': 0, 'prec_period': 360,
                    'cloudness': 0.5, 'prec_type': 0, 'prec_strength': 0, 'icon': 'bkn_d', 'condition': 'cloudy',
                    'feels_like': 7, 'daytime': 'd', 'polar': False, 'fresh_snow_mm': 0},
        'day_short': {'_source': '6,9,12,15,18,21', 'temp': 12, 'temp_min': 4, 'wind_speed': 3.5, 'wind_gust': 7.3,
                      'wind_dir': 'nw', 'pressure_mm': 755, 'pressure_pa': 1006, 'humidity': 50, 'soil_temp': 6,
                      'soil_moisture': 0.34, 'prec_mm': 0, 'prec_prob': 0, 'prec_period': 1080, 'cloudness': 0.5,
                      'prec_type': 0, 'prec_strength': 0, 'icon': 'bkn_d', 'condition': 'cloudy', 'feels_like': 4,
                      'daytime': 'd', 'polar': False, 'fresh_snow_mm': 0},
        'morning': {'_source': '6,9', 'temp_min': 4, 'temp_avg': 6, 'temp_max': 8, 'wind_speed': 3.4, 'wind_gust': 7.1,
                    'wind_dir': 'nw', 'pressure_mm': 756, 'pressure_pa': 1007, 'humidity': 65, 'soil_temp': 4,
                    'soil_moisture': 0.34, 'prec_mm': 0, 'prec_prob': 0, 'prec_period': 360, 'cloudness': 0.5,
                    'prec_type': 0, 'prec_strength': 0, 'icon': 'bkn_d', 'condition': 'cloudy', 'feels_like': 2,
                    'daytime': 'd', 'polar': False, 'fresh_snow_mm': 0}}, 'hours': []}]}
